apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2020-01-30T08:17:04.175507
    commit.stack.appsody.dev/author: kilnerm <38245247+kilnerm@users.noreply.github.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/nodejs
    commit.stack.appsody.dev/date: Fri Feb 21 17:32:05 2020 +0000
    commit.stack.appsody.dev/message: 'Merge pull request #293 from groeges/release-0.6'
    description: This image contains the Kabanero development stack for the Nodejs
      collection
    distribution-scope: public
    help: For more information visit https://github.com/sclorg/s2i-nodejs-container
    image.opencontainers.org/created: "2020-02-21T17:19:16-05:00"
    k8s.io/description: Node.js 12 available as container is a base platform for building
      and running various Node.js 12 applications and frameworks. Node.js is a platform
      built on Chrome's JavaScript runtime for easily building fast, scalable network
      applications. Node.js uses an event-driven, non-blocking I/O model that makes
      it lightweight and efficient, perfect for data-intensive real-time applications
      that run across distributed devices.
    k8s.io/display-name: Node.js 12
    maintainer: SoftwareCollections.org <sclorg@redhat.com>
    name: kabanero/nodejs
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,nodejs,nodejs12
    redhat.com/build-host: cpt-1001.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: nodejs-12-container
    redhat.com/deployments-dir: /opt/app-root/src
    redhat.com/dev-mode: DEV_MODE:false
    redhat.com/dev-mode.port: DEBUG_PORT:5858
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "27"
    s2i.io/scripts-url: image:///usr/libexec/s2i
    s2i.openshift.io/scripts-url: image:///usr/libexec/s2i
    stack.appsody.dev/authors: Sam Roberts <vieuxtech@gmail.com>
    stack.appsody.dev/configured: docker.io/kabanerobeta/nodejs:0.3
    stack.appsody.dev/created: "2020-02-21T18:09:43Z"
    stack.appsody.dev/description: Runtime for Node.js applications
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/release-0.6/incubator/nodejs/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 184e367afb4c3aa906f2a8daf7ebed70168e0a82
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/release-0.6/incubator/nodejs/image
    stack.appsody.dev/tag: docker.io/kabanerobeta/nodejs:0.3.2
    stack.appsody.dev/title: Node.js
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/release-0.6/incubator/nodejs
    summary: Image for Kabanero Nodejs development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/nodejs-12/images/1-27
    usage: s2i build <SOURCE-REPOSITORY> ubi8/nodejs-12:latest <APP-NAME>
    vcs-ref: 9a85b86edcc6c765692f15311abe259b0f9997b2
    vcs-type: git
    vendor: Kabanero
    version: 0.3.1
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-nodejs
    stack.appsody.dev/id: nodejs
    stack.appsody.dev/version: 0.3.2
  name: sample-nodejs
spec:
  applicationImage: dev.local/sample-nodejs
  createKnativeService: true
  expose: true
  service:
    port: 3000
    type: NodePort
  stack: nodejs
  version: 1.0.0
status: {}
